### ISSUE TITLE
EE专业课没有在主菜单里

### ISSUE THREAD

**Issue by sayoriaaa** [sayoriaaa/nbu-icicles#5]
EE专业课没有在主菜单里，且建议将CS/EE专业课的课程同时添加到本科生课程目录下。 @lindocedskes

**Comment by lindocedskes** [comment]
mkdocs.yml 里nav字段对应添加即可，已修复

**Comment by sayoriaaa** [comment]
> 同时添加到本科生课程目录，会造成3级目录，mkdocs.yml 里nav字段似乎只支持2级目录（3级的有需要再想解决，目前就CS/EE，还能接受

OK
